apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: krateo.io
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.registry.images.auth }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: krateo-uri-config
          env:
            - name: 'auth_LEVEL'
              value: {{ .Values.auth.level }}
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  name: krateo-secret
                  key: MONGODB_URI
      imagePullSecrets:
        - name: registry-credentials
