apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: krateo.io
    component: auth
spec:
  selector:
    component: auth
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080